### ISSUE TITLE
关于多音字问题

### ISSUE THREAD

**Issue by 981530125** [xinglie/pinyin#4]
请问有办法优化下吗?,写的太全了,比如其,有两种读音ji和qi,一般读qi比较多

**Comment by xinglie** [comment]
就汉字转拼音来讲，这个没办法处理。
所以我在api上保留了遇到多音字时的回调，可以在回调中对多音字进行处理，可能需要引入第三方的常用词拼音库之类的

**Comment by xinglie** [comment]
@981530125 如果不关心文件大小，可以看下 https://github.com/hotoo/pinyin 它自带词库来解决多音字的问题
