### ISSUE TITLE
请问作者大大怎么不发布到npm仓库？

### ISSUE THREAD

**Issue by YangGoldDragon** [xinglie/pinyin#5]
如题。
另外还有一个小问题，这里的汉字好像比别人的少了几十个，不知道为啥，我看到别人的都是20950左右。

**Comment by xinglie** [comment]
@YangGoldDragon 汉字的范围最常用的在 \u4e00-\u9fa5 这个区间里，其它区间的暂不考虑。这个区间有20928个汉字(后来经我资料查找，发现这个区间里有些汉字并没有对应的拼音，也有些汉字无法正常显示，所以被我精简到了20870个汉字了

**Comment by xinglie** [comment]
@YangGoldDragon 因为npm上拼音相关的库特别多，好多想取的名字都被占用了。而且我这个主要是解决文件大小的问题，功能上也没其它库丰富，所以就没放到npm上

**Comment by YangGoldDragon** [comment]
> @YangGoldDragon 因为npm上拼音相关的库特别多，好多想取的名字都被占用了。而且我这个主要是解决文件大小的问题，功能上也没其它库丰富，所以就没放到npm上

哦哦，原来是这样，感谢作者大大回复。
